export const FACULTIES_LOADING = 'FACULTIES_LOADING';
export const FACULTIES_SUCCESS = 'FACULTIES_SUCCESS';
export const FACULTIES_ERROR = 'FACULTIES_ERROR';

export const SET_SINGLE_FACULT = 'SET_SINGLE_FACULT';

export const SINGLE_FACULTIY_SUCCESS = 'SINGLE_FACULTIY_SUCCESS';
export const SINGLE_FACULTY_ERROR = 'SINGLE_FACULTY_ERROR';

export const STUDENT_STATUSES_LOAD_SUCCESS = 'STUDENT_STATUSES_LOAD_SUCCESS';
export const INDUSTRY_DATA_LOAD_SUCCESS = 'INDUSTRY_DATA_LOAD_SUCCESS';
export const ENROLMENTS_LOAD_SUCCESS = 'ENROLMENTS_LOAD_SUCCESS';
export const INTERNALDEADLINES_LOAD_SUCCESS = 'INTERNALDEADLINES_LOAD_SUCCESS';
export const ENROLMENTSTRATEGIES_LOAD_SUCCESS =
  'ENROLMENTSTRATEGIES_LOAD_SUCCESS';
export const HISTORICPERFORMANCE_LOAD_SUCCESS =
  'HISTORICPERFORMANCE_LOAD_SUCCESS';
export const INSTITUTIONALDEADLINES_LOAD_SUCCESS =
  'INSTITUTIONALDEADLINES_LOAD_SUCCESS';

export const ENROLMENTS_UPDATE_LOADING = 'ENROLMENTS_UPDATE_LOADING';
export const ENROLMENTS_UPDATE_SUCCESS = 'ENROLMENTS_UPDATE_SUCCESS';
export const ENROLMENTS_UPDATE_ERROR = 'ENROLMENTS_UPDATE_ERROR';

export const CHANGE_ENROLMENTS_DATA = 'CHANGE_ENROLMENTS_DATA';
export const CHANGE_STUDENTSTATUS_DATA = 'CHANGE_STUDENTSTATUS_DATA';

export const STUDENTSTATUSES_UPDATE_LOADING = 'STUDENTSTATUSES_UPDATE_LOADING';
export const STUDENTSTATUSES_UPDATE_SUCCESS = 'STUDENTSTATUSES_UPDATE_SUCCESS';
export const STUDENTSTATUSES_UPDATE_ERROR = 'STUDENTSTATUSES_UPDATE_ERROR';

export const INTERNALDEADLINE_DELETE_LOADING =
  'INTERNALDEADLINE_DELETE_LOADING';
export const INTERNALDEADLINE_DELETE_SUCCESS =
  'INTERNALDEADLINE_DELETE_SUCCESS';
export const INTERNALDEADLINE_DELETE_ERROR = 'INTERNALDEADLINE_DELETE_ERROR';

export const INTERNALDEADLINE_UPDATE_LOADING =
  'INTERNALDEADLINE_UPDATE_LOADING';
export const INTERNALDEADLINE_UPDATE_SUCCESS =
  'INTERNALDEADLINE_UPDATE_SUCCESS';
export const INTERNALDEADLINE_UPDATE_ERROR = 'INTERNALDEADLINE_UPDATE_ERROR';

export const CHANGE_INTERNALDEADLINE_DATA = 'CHANGE_INTERNALDEADLINE_DATA';
export const INTERNALDEADLINE_ADD_DEADLINE = 'INTERNALDEADLINE_ADD_DEADLINE';

// Institutional Deadlines
export const INSTITUTIONALDEADLINE_UPDATE_LOADING =
  'INSTITUTIONALDEADLINE_UPDATE_LOADING';
export const INSTITUTIONALDEADLINE_UPDATE_SUCCESS =
  'INSTITUTIONALDEADLINE_UPDATE_SUCCESS';
export const INSTITUTIONALDEADLINE_UPDATE_ERROR =
  'INSTITUTIONALDEADLINE_UPDATE_ERROR';

export const INSTITUTIONAL_UPDATE_LOADING = 'INSTITUTIONAL_UPDATE_LOADING';
export const INSTITUTIONAL_UPDATE_SUCCESS = 'INSTITUTIONAL_UPDATE_SUCCESS';
export const INSTITUTIONAL_UPDATE_ERROR = 'INSTITUTIONAL_UPDATE_ERROR';

export const CHANGE_INSTITUTIONALDEADLINE_DATA =
  'CHANGE_INSTITUTIONALDEADLINE_DATA';

export const INSTITUTIONALDEADLINE_ADD_DEADLINE =
  'INSTITUTIONALDEADLINE_ADD_DEADLINE';

export const INSTITUTIONALDEADLINE_DELETE_LOADING =
  'INSTITUTIONALDEADLINE_DELETE_LOADING';
export const INSTITUTIONALDEADLINE_DELETE_SUCCESS =
  'INSTITUTIONALDEADLINE_DELETE_SUCCESS';
export const INSTITUTIONALDEADLINE_DELETE_ERROR =
  'INSTITUTIONALDEADLINE_DELETE_ERROR';
