export const FACULTIES_LOADING = 'FACULTIES_LOADING';
export const FACULTIES_SUCCESS = 'FACULTIES_SUCCESS';
export const FACULTIES_ERROR = 'FACULTIES_ERROR';

export const SET_SINGLE_FACULT = 'SET_SINGLE_FACULT';

export const SINGLE_FACULTIY_SUCCESS = 'SINGLE_FACULTIY_SUCCESS';
export const SINGLE_FACULTY_ERROR = 'SINGLE_FACULTY_ERROR';

export const STUDENT_STATUSES_LOAD_SUCCESS = 'STUDENT_STATUSES_LOAD_SUCCESS';
export const INDUSTRY_DATA_LOAD_SUCCESS = 'INDUSTRY_DATA_LOAD_SUCCESS';
export const ENROLMENTS_LOAD_SUCCESS = 'ENROLMENTS_LOAD_SUCCESS';
export const INTERNALDEADLINES_LOAD_SUCCESS = 'INTERNALDEADLINES_LOAD_SUCCESS';
export const ENROLMENTSTRATEGIES_LOAD_SUCCESS =
  'ENROLMENTSTRATEGIES_LOAD_SUCCESS';
export const HISTORICPERFORMANCE_LOAD_SUCCESS =
  'HISTORICPERFORMANCE_LOAD_SUCCESS';
export const INSTITUTIONALDEADLINES_LOAD_SUCCESS =
  'INSTITUTIONALDEADLINES_LOAD_SUCCESS';
