export const LOGIN_USER_LOADING = 'LOGIN_USER_LOADING';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const LOAD_USERDATA_LOADING = 'LOAD_USERDATA_LOADING';
export const LOAD_USERDATA_SUCCESS = 'LOAD_USERDATA_SUCCESS';
export const LOAD_USERDATA_ERROR = 'LOAD_USERDATA_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';
